# Railway.app configuration
# This file configures deployment for Railway

[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/test-db"
healthcheckTimeout = 30
restartPolicyType = "on-failure"

[env]
NODE_ENV = "production"
PORT = { from = "PORT", default = "3000" }
