# Render.com deployment configuration
services:
  - type: web
    name: hrms-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          property: port
    healthCheckPath: /test-db
